version: "3"

services:
  office-tool-backend:
    build:
      context: .
    container_name: office-tool-backend
    image: office-tool-backend
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "8000:8000"
    volumes:
      - "./:/app"

networks:
  app-network:
    driver: bridge
