org: nachetfalter
app: office-tool-backend
service: office-tool-backend

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-southeast-2
  memorySize: 7168
  apiGateway:
    binaryMediaTypes:
      - 'application/zip'
      - 'application/pdf'
      - 'application/octet-stream'
      - 'multipart/form-data'

custom:
  prune:
    automatic: true
    includeLayers: true
    number: 2

functions:
  backend:
    handler: dist/router/router.handler
    events:
      - http:
          path: /pdf/split
          method: POST
          cors: true
      - http:
          path: /pdf/merge
          method: POST
          cors: true
      - http:
          path: /uploadUrl
          method: GET
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
    layers:
      - arn:aws:lambda:ap-southeast-2:175033217214:layer:graphicsmagick:2

plugins:
  - serverless-prune-plugin
