org: nachetfalter
app: office-tool-backend
service: office-tool-backend

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-southeast-2
  memorySize: 7168
  apiGateway:
    binaryMediaTypes:
      - 'application/zip'
      - 'application/pdf'
      - 'application/octet-stream'
      - 'multipart/form-data'
custom:
  serverless-offline:
    httpPort: 8000
  noPrependStageInUrl: true

functions:
  backend:
    handler: dist/app.handler
    events:
      - http:
          path: /pdf/split
          method: POST
          cors: true
      - http:
          path: /test
          method: GET
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
    layers:
      - arn:aws:lambda:ap-southeast-2:764866452798:layer:ghostscript:9
      - arn:aws:lambda:ap-southeast-2:175033217214:layer:graphicsmagick:2

plugins:
  - serverless-offline
