name: office-tool-backend-cicd

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn

      - name: Install Ghostscript and Graphicsmagick
        run: sudo apt-get update && sudo apt-get install ghostscript && sudo apt-get install graphicsmagick

      - name: Run the tests
        run: yarn test
        env:
          ENVIRONMENT: ''

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

      - name: Deploy to AWS
        uses: serverless/github-action@master
        with:
          args: deploy
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.ACTION_SERVERLESS_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.ACTION_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ACTION_AWS_SECRET_ACCESS_KEY }}
          CI: ''
          EFS_ARN: ${{ secrets.EFS_ARN }}
          VPC_SECURITY_GROUP: ${{ secrets.VPC_SECURITY_GROUP }}
          VPC_SUBNET_ID: ${{ secrets.VPC_SUBNET_ID }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          S3_RESOURCE: ${{ secrets.S3_RESOURCE }}
